### ISSUE TITLE
make this app responsive .

### ISSUE THREAD

**Issue by kushalShukla-web** [kushalShukla-web/amazon-clone#2]
currently this app is not responsive , so make it .
![image](https://user-images.githubusercontent.com/85934954/140026474-19db4b57-989b-4a2a-8558-907ce282ae8c.png)
as u can see that divs are not arranged in  a proper way so make it too .

if anyone have problem in installation pls feel free to ask .

**Comment by lcnhut070200** [comment]
<img width="1552" alt="Screen Shot 2021-11-05 at 15 53 01" src="https://user-images.githubusercontent.com/58385680/140484072-a8538ab6-0373-462a-9e99-0fc04177078b.png">

Is that what you mean?

**Comment by kushalShukla-web** [comment]
yep @lcnhut070200
